export const ADD_TO_CART = "ADD_TO_CART";

export const INSREASE_COUNT_IN_CART ="INSREASE_COUNT_IN_CART";

export const DESREASE_COUNT_IN_CART ="DESREASE_COUNT_IN_CART";

export const DELETE_FROM_CART = "DELETE_FROM_CART";

export const CLEAR_CART = "CLEAR_CART";